---
- name: For Debian
  include: nginx_debian.yaml
  when: ansible_os_family == 'Debian'

- name: For Centos
  include: nginx_centos.yaml
  when: ansible_os_family == "Centos"

- name: check connection
  wait_for:
    host: "localhost"
    port: "80"
    state: started
    delay: 0
    timeout: 3
- name: url Check
  uri:
    uri: http://localhost
    return_content: yes
  register: this
- debug:
    msg: "{{ this }}"